# Joint limits configuration for robot teleoperation
# All values in radians

joint_limits:
  joint_0:
    min: -3.14159  # -π
    max: 3.14159   # π
    name: "Base rotation"
    
  joint_1:
    min: -1.5708   # -π/2
    max: 1.5708    # π/2
    name: "Shoulder pitch"
    
  joint_2:
    min: -1.5708   # -π/2
    max: 1.5708    # π/2
    name: "Elbow pitch"
    
  joint_3:
    min: -3.14159  # -π
    max: 3.14159   # π
    name: "Wrist roll"
    
  joint_4:
    min: -1.5708   # -π/2
    max: 1.5708    # π/2
    name: "Wrist pitch"
    
  joint_5:
    min: -3.14159  # -π
    max: 3.14159   # π
    name: "Wrist yaw"

# Optional: Joint mapping for reordering joints between robots
# Example: Map leader joint 0 to follower joint 2, etc.
# joint_mapping:
#   0: 2
#   1: 0
#   2: 1
#   3: 3
#   4: 4
#   5: 5

# Optional: Transformation matrix for joint values
# Example: 6x6 identity matrix (no transformation)
# transformation_matrix:
#   - [1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
#   - [0.0, 1.0, 0.0, 0.0, 0.0, 0.0]
#   - [0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
#   - [0.0, 0.0, 0.0, 1.0, 0.0, 0.0]
#   - [0.0, 0.0, 0.0, 0.0, 1.0, 0.0]
#   - [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]