# Example configurations showing different mapping and transformation scenarios

# Example 1: Simple joint reordering
# Use when robots have joints in different order
reorder_example:
  joint_mapping:
    0: 2  # Leader joint 0 -> Follower joint 2
    1: 0  # Leader joint 1 -> Follower joint 0  
    2: 1  # Leader joint 2 -> Follower joint 1
    3: 3  # Leader joint 3 -> Follower joint 3 (same)
    4: 5  # Leader joint 4 -> Follower joint 5
    5: 4  # Leader joint 5 -> Follower joint 4
  
  joint_offsets:
    - 0.0   # No offsets
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

# Example 2: Mirror operation
# Mirror the leader robot for symmetric operation
mirror_example:
  joint_mapping:
    0: 0   # Base stays same
    1: 1   # Shoulder stays same
    2: 2   # Elbow stays same
    3: 3   # Wrist roll stays same
    4: 4   # Wrist pitch stays same
    5: 5   # Wrist yaw stays same
  
  transformation_matrix:
    - [-1.0, 0.0,  0.0,  0.0,  0.0,  0.0]   # Flip base
    - [0.0,  1.0,  0.0,  0.0,  0.0,  0.0]   # Keep shoulder
    - [0.0,  0.0, -1.0,  0.0,  0.0,  0.0]   # Flip elbow
    - [0.0,  0.0,  0.0,  1.0,  0.0,  0.0]   # Keep wrist roll
    - [0.0,  0.0,  0.0,  0.0, -1.0,  0.0]   # Flip wrist pitch
    - [0.0,  0.0,  0.0,  0.0,  0.0,  1.0]   # Keep wrist yaw

# Example 3: Calibration offsets
# Add offsets to compensate for different zero positions
calibration_example:
  joint_offsets:
    - 0.087   # 5 degrees offset for base
    - -0.175  # -10 degrees offset for shoulder
    - 0.262   # 15 degrees offset for elbow
    - -0.087  # -5 degrees offset for wrist roll
    - 0.175   # 10 degrees offset for wrist pitch
    - 0.0     # No offset for wrist yaw

# Example 4: Complex transformation with everything
# Reorder + scale + offset
full_transformation_example:
  joint_limits:
    joint_0: {min: -3.14, max: 3.14}
    joint_1: {min: -1.57, max: 1.57}
    joint_2: {min: -2.09, max: 2.09}
    joint_3: {min: -3.14, max: 3.14}
    joint_4: {min: -1.57, max: 1.57}
    joint_5: {min: -3.14, max: 3.14}
  
  joint_mapping:
    0: 1  # Leader base -> Follower shoulder
    1: 0  # Leader shoulder -> Follower base
    2: 2  # Leader elbow -> Follower elbow (same)
    3: 4  # Leader wrist roll -> Follower wrist pitch
    4: 3  # Leader wrist pitch -> Follower wrist roll
    5: 5  # Leader wrist yaw -> Follower wrist yaw (same)
  
  transformation_matrix:
    # After mapping, apply scaling
    - [0.8,  0.0,  0.0,  0.0,  0.0,  0.0]   # Scale mapped joint 0 by 80%
    - [0.0,  1.2,  0.0,  0.0,  0.0,  0.0]   # Scale mapped joint 1 by 120%
    - [0.0,  0.0,  1.0,  0.0,  0.0,  0.0]   # No scaling for joint 2
    - [0.0,  0.0,  0.0, -1.0,  0.0,  0.0]   # Invert mapped joint 3
    - [0.0,  0.0,  0.0,  0.0,  0.9,  0.0]   # Scale mapped joint 4 by 90%
    - [0.0,  0.0,  0.0,  0.0,  0.0,  1.0]   # No scaling for joint 5
  
  joint_offsets:
    # After mapping and scaling, add offsets
    - 0.1     # Add offset to final joint 0
    - -0.05   # Subtract offset from final joint 1
    - 0.0     # No offset for joint 2
    - 0.087   # Add 5° offset to final joint 3
    - 0.0     # No offset for joint 4
    - -0.1    # Subtract offset from final joint 5

# Example 5: Different robot types
# Configuration for converting from 6-DOF arm to different robot
different_robot_example:
  # Map 6-DOF arm to robot with different joint arrangement
  joint_mapping:
    0: 0   # Base rotation
    1: 1   # First joint
    2: 2   # Second joint  
    3: 3   # Third joint
    4: 4   # Fourth joint
    5: 5   # Fifth joint
  
  # Scale all joints to smaller ranges for safety
  transformation_matrix:
    - [0.5,  0.0,  0.0,  0.0,  0.0,  0.0]   # 50% range
    - [0.0,  0.7,  0.0,  0.0,  0.0,  0.0]   # 70% range
    - [0.0,  0.0,  0.6,  0.0,  0.0,  0.0]   # 60% range
    - [0.0,  0.0,  0.0,  0.8,  0.0,  0.0]   # 80% range
    - [0.0,  0.0,  0.0,  0.0,  0.5,  0.0]   # 50% range
    - [0.0,  0.0,  0.0,  0.0,  0.0,  0.7]   # 70% range
  
  joint_offsets:
    # Add small offsets for better starting position
    - 0.05
    - 0.0
    - -0.1
    - 0.0
    - 0.05
    - 0.0

# Example 6: Swapping specific joints
# Swap shoulder and elbow for different kinematic chain
swap_joints_example:
  joint_mapping:
    0: 0   # Base stays
    1: 2   # Leader shoulder -> Follower elbow  
    2: 1   # Leader elbow -> Follower shoulder
    3: 3   # Wrist roll stays
    4: 4   # Wrist pitch stays
    5: 5   # Wrist yaw stays
  
  # Adjust ranges after swapping
  transformation_matrix:
    - [1.0,  0.0,  0.0,  0.0,  0.0,  0.0]
    - [0.0,  1.5,  0.0,  0.0,  0.0,  0.0]   # Increase range for swapped joint
    - [0.0,  0.0,  0.8,  0.0,  0.0,  0.0]   # Decrease range for swapped joint
    - [0.0,  0.0,  0.0,  1.0,  0.0,  0.0]
    - [0.0,  0.0,  0.0,  0.0,  1.0,  0.0]
    - [0.0,  0.0,  0.0,  0.0,  0.0,  1.0]