# Test configuration with restrictive limits for debugging
# Some joints have very tight limits to test the blocking feature

joint_limits:
  joint_0:
    min: -1.0      # Restrictive limit (will block values < -1.0)
    max: 1.0       # Restrictive limit (will block values > 1.0)
    name: "Base rotation - RESTRICTED"
    
  joint_1:
    min: -0.5      # Very restrictive 
    max: 0.5       # Very restrictive
    name: "Shoulder pitch - VERY RESTRICTED"
    
  joint_2:
    min: -1.5708   # -π/2
    max: 1.5708    # π/2
    name: "Elbow pitch - NORMAL"
    
  joint_3:
    min: -3.14159  # -π
    max: 3.14159   # π
    name: "Wrist roll - FULL RANGE"
    
  joint_4:
    min: -0.3      # Very restrictive for testing
    max: 0.3       # Very restrictive for testing
    name: "Wrist pitch - TEST RESTRICTED"
    
  joint_5:
    min: -3.14159  # -π
    max: 3.14159   # π
    name: "Wrist yaw - FULL RANGE"

# Optional: Test joint mapping (reorder joints)
# Uncomment to test joint reordering
# joint_mapping:
#   0: 0
#   1: 1
#   2: 2
#   3: 3
#   4: 4
#   5: 5

# Optional: Test transformation (scale down joint 1 by half)
# Uncomment to test transformations
# transformation_matrix:
#   - [1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
#   - [0.0, 0.5, 0.0, 0.0, 0.0, 0.0]  # Scale joint 1 by 0.5
#   - [0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
#   - [0.0, 0.0, 0.0, 1.0, 0.0, 0.0]
#   - [0.0, 0.0, 0.0, 0.0, 1.0, 0.0]
#   - [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]